language: java
jdk:
- oraclejdk17

services:
  - docker
  
before_install:
- mvn clean package
- docker build -t babadgunia/sms-back .
- docker build -t babadgunia/sms-db -f src/main/resources/db/Dockerfile .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master